---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apt-swarm
spec:
  replicas: 1

  selector:
    matchLabels:
      name: apt-swarm

  template:
    metadata:
      labels:
        name: apt-swarm

    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: apt-swarm
          image: ghcr.io/kpcyrd/apt-swarm:edge
          args: ["p2p", "--check-container-updates", "ghcr.io/kpcyrd/apt-swarm:edge"]
          imagePullPolicy: Always
          # TODO: how do I configure `init: true`?
          volumeMounts:
            - name: apt-swarm-pvc
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: apt-swarm-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: apt-swarm
spec:
  type: NodePort
  selector:
    name: apt-swarm
  ports:
    - protocol: TCP
      port: 16169
      targetPort: 16169
