[package]
name = "apt-swarm"
version = "0.1.0"
description = "Work in progress p2p gossip network for update transparency 🥸"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/kpcyrd/apt-swarm"
categories = ["command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bstr = "1.2.0"
bytes = "1.4.0"
clap = { version = "4.0.32", features = ["derive", "env"] }
clap_complete = "4.0.7"
colored = "2.0.0"
dirs = "4.0.0"
env_logger = "0.10.0"
log = "0.4.17"
memchr = "2.5.0"
reqwest = { version = "0.11.13", features = ["rustls-tls"], default-features = false }
sequoia-openpgp = "1.12.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
sha2 = "0.10.6"
sled = { version = "0.34.7", features = ["compression"] }
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread", "io-util", "io-std", "fs"] }
toml = "0.7.1"
