[package]
name = "apt-swarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive", "env"] }
clap_complete = "4.0.7"
dirs = "4.0.0"
env_logger = "0.10.0"
log = "0.4.17"
memchr = "2.5.0"
reqwest = { version = "0.11.13", features = ["rustls-tls"], default-features = false }
sequoia-openpgp = "1.12.0"
sha2 = "0.10.6"
sled = { version = "0.34.7", features = ["compression"] }
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread", "io-util", "io-std", "fs"] }
