[package]
name = "apt-swarm"
version = "0.2.0"
description = "🥸 p2p gossip network for update transparency, based on pgp 🥸"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/kpcyrd/apt-swarm"
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.64"
bstr = "1.2.0"
bytes = "1.4.0"
clap = { version = "4.0.32", features = ["derive", "env"] }
clap_complete = "4.0.7"
colored = "2.0.0"
dirs = "4.0.0"
env_logger = "0.10.0"
fastrand = "1.9.0"
futures = "0.3.26"
getrandom = "0.2.8"
git-object = "0.26.2"
gix = "0.37.1"
hex = "0.4.3"
irc = { version = "0.15.0", default-features = false, features = ["tls-rust"] }
log = "0.4.17"
memchr = "2.5.0"
num-format = "0.4.4"
reqwest = { version = "0.11.13", features = ["rustls-tls"], default-features = false }
sequoia-openpgp = "1.12.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
sha2 = "0.10.6"
sled = { version = "0.34.7", features = ["compression"] }
socket2 = "0.4.7"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread", "io-util", "io-std", "fs", "process"] }
toml = "0.7.1"
